---
booktitle: Proceedings of The 3rd Conference on Lifelong Learning Agents
shortname: CoLLAs
year: '2024'
volume: '274'
start: &1 2024-07-29
end: 2024-08-01
published: 2025-02-17
conference_number: '3'
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CoLLAs-2024
month: 0
cycles: false
bibtex_editor: Lomonaco, Vincenzo and Melacci, Stefano and Tuytelaars, Tinne and Chandar,
  Sarath and Pascanu, Razvan
editor:
- given: Vincenzo
  family: Lomonaco
- given: Stefano
  family: Melacci
- given: Tinne
  family: Tuytelaars
- given: Sarath
  family: Chandar
- given: Razvan
  family: Pascanu
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The 3rd Conference on Lifelong Learning Agents
    Held in University of Pisa, Pisa, Italy on 29 July to 01 August 2024

  Published as Volume 274 by the Proceedings of Machine Learning Research on 17 February 2025.

  Volume Edited by:
    Vincenzo Lomonaco
    Stefano Melacci
    Tinne Tuytelaars
    Sarath Chandar
    Razvan Pascanu

  Series Editors:
    Neil D. Lawrence
date_str: 29 Jul--01 Aug
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v274"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v274
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v274
email: ''
conference:
  name: Conference on Lifelong Learning Agents
  url: https://lifelong-ml.cc/
  location: University of Pisa, Pisa, Italy
  dates:
  - *1
  - 2024-07-30
  - 2024-07-31
  - 2024-08-01
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v274/Collas2024_processed.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v274/Collas2024_processed.bib
